// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMAKj5MAVUl37BQQ3TK87hci6CCbAZAI',
    appId: '1:924004577795:web:c26ac5251ded43e922d436',
    messagingSenderId: '924004577795',
    projectId: 'dashboard-app-30393',
    authDomain: 'dashboard-app-30393.firebaseapp.com',
    storageBucket: 'dashboard-app-30393.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsyjoeVvc6Q1ZD1rCs6_HhvYrSeaJI2U4',
    appId: '1:924004577795:android:372216808776260622d436',
    messagingSenderId: '924004577795',
    projectId: 'dashboard-app-30393',
    storageBucket: 'dashboard-app-30393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvEjebQmigvs12LO42_Fo45CEE_pwLv38',
    appId: '1:924004577795:ios:4ab4ded7de491f4122d436',
    messagingSenderId: '924004577795',
    projectId: 'dashboard-app-30393',
    storageBucket: 'dashboard-app-30393.appspot.com',
    iosBundleId: 'com.example.dashboardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvEjebQmigvs12LO42_Fo45CEE_pwLv38',
    appId: '1:924004577795:ios:4ab4ded7de491f4122d436',
    messagingSenderId: '924004577795',
    projectId: 'dashboard-app-30393',
    storageBucket: 'dashboard-app-30393.appspot.com',
    iosBundleId: 'com.example.dashboardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsMAKj5MAVUl37BQQ3TK87hci6CCbAZAI',
    appId: '1:924004577795:web:4b6aba891bc4496922d436',
    messagingSenderId: '924004577795',
    projectId: 'dashboard-app-30393',
    authDomain: 'dashboard-app-30393.firebaseapp.com',
    storageBucket: 'dashboard-app-30393.appspot.com',
  );
}
